GET http://localhost:5500/
Content-Type: application/json
###

GET http://localhost:5500/list
Content-Type: application/json
###

GET http://localhost:5500/manual
Content-Type: application/json
###

POST http://localhost:5500/add HTTP/1.1
Content-Type: application/json

{
    "title":"Boiling snakes",
    "date":"10/90/22"
}
###